spring.application.name=backend
server.port = 9000

spring.datasource.url=jdbc:mysql://localhost:3307/tech_match
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=8f4d9c2e7a1b5f6d3e8c9a2f7b1d4e6a9c3f5b7d2e8a1f4c6b9d7e3a5f8c2d1